openapi: 3.0.0
info:
  title: Trails API
  version: 1.0.0
servers:
  - url: http://localhost:5000
  
paths:
  /trails:
    get:
      summary: Get all trails
      operationId: app.routes.get_trails
      responses:
        "200":
          description: A list of trails
    post:
      summary: Add a new trail
      operationId: app.routes.add_trail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trail'
      responses:
        "201":
          description: Trail added
  /trails/{trail_id}:
    put:
      summary: Update a trail
      operationId: app.routes.update_trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trail'
      responses:
        "200":
          description: Trail updated
    delete:
      summary: Delete a trail
      operationId: app.routes.delete_trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Trail deleted
components:
  schemas:
    Trail:
      type: object
      properties:
        Trail_Name:
          type: string
        Trail_Description:
          type: string
        Trail_Type:
          type: string
        Trail_Difficulty:
          type: string
        Trail_Distance:
          type: number
        Trail_Elevation_Gain:
          type: number
        Trail_Length:
          type: integer
        Trail_Rating:
          type: number
        Trail_City_ID:
          type: integer
        Trail_Creator:
          type: integer
